# Lineare Optimierung in Python
Wir wollen hier kurz kennenlernen, wie man lineare Optimierungsprobleme in Python lösen kann.

Zuerst müssen wir Python-Module laden, die dafür nötig sind. Das Modul `numpy` unterstützt numerische Rechnungen in Python, z.B. Rechnen mit Matrizen, Vektoren und das Lösen von Gleichungssystemen.

In [1]:
import numpy as np
from scipy.optimize import linprog

Wir wollen nun das Problem
\begin{align*}
\text{Minimiere} &\quad c^\top x \\
\text{u.d.N.} &\quad A x = b \\
&\quad x \ge 0
\end{align*}
lösen. Dabei wollen wir die Daten
$$
A =
\begin{pmatrix} 2 & 1 & 2 \\ 5 & 3 & 4 \end{pmatrix},
\quad
b =
\begin{pmatrix} 3 \\ 8 \end{pmatrix},
\quad
c =
\begin{pmatrix} 16 \\ 9 \\ 18 \end{pmatrix}
$$
nutzen.

Matrizen können mittels `np.array` angelegt werden. Dabei ist die Matrix *zeilenweise* zu übergeben.

In [2]:
A = np.array([[2,1,2],[5,3,4]])

Nun können wir überprüfen, ob das funktioniert hat.

In [3]:
print(A)

[[2 1 2]
 [5 3 4]]


Analog können wir die Vektoren $b$ und $c$ anlegen.

In [4]:
c = np.array([16,9,18])
b = np.array([3,8])

Jetzt können wir das Optimierungsproblem mittels `linprog` lösen. Diese Methode kann auch Ungleichungsnebenbedingungen $A x \le b$ behandeln, daher müssen wir mittels `A_eq` und `b_eq` spezifizieren, dass dies Gleichungsnebenbedingungen sind. Die Dokumentation dieser Routine findet man [hier](https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.linprog.html).

In [5]:
solution = linprog(c, A_eq = A, b_eq = b, options={'disp':True})

Optimization terminated successfully.
         Current function value: 25.000000   
         Iterations: 2


Der Rückgabewert `solution` enthält:

In [6]:
print(solution)

     fun: 25.0
 message: 'Optimization terminated successfully.'
     nit: 2
   slack: array([], dtype=float64)
  status: 0
 success: True
       x: array([1., 1., 0.])


Da die duale Lösung nicht enthalten ist, müssen wir diese selbst erstellen. Dazu konstruieren wir zuerst die Basis $J$. Die Basisvariablen sind die ersten beiden Komponenten in $x$. **Nun ist aber zu beachten, dass die Indizes in Python mit $0$ beginnen!** Daher ist $J = (0, 1)$.

In [7]:
J = [0,1]

Um dies zu Überprüfen, berechnen wir nochmals die Basisvariablen $x^*_J = A_J^{-1} b$. Die Matrix $A_J$ erhalten wir mittels `A[:,J]`. Der `:` steht dafür, dass wir alle Zeilen auswählen und das `J` steht dafür, dass wir nur die Spalten aus `J` auswählen. Das Lösen des Gleichungssystems geschieht mittels `np.linalg.solve`.

In [8]:
np.linalg.solve(A[:,J], b)

array([1., 1.])

Die duale Lösung erhalten wir nun mittels $y = A_J^{-\top} c_J$.

In [13]:
y = np.linalg.solve(A[:,J].T, c[J])
y

array([3., 2.])